import CarrouselMovies from "@/components/carrouselMovies/carrouselMovies";
import Modal from "@/components/modal/modal";
import { msgBody } from "@/utils/strings";
import Head from "next/head";
import {
  serviceGetPopularMovies,
  serviceGetTopRatedMovies,
  serviceGetUpcomingMovies,
} from "@/services/movies";
import Alog from "@/components/render/alog";
const data = {
  bar: 4,
  val: null,
};
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Orbitron&family=Pacifico&family=Pragati+Narrow&family=Roboto:wght@300&display=swap" rel="stylesheet"> */}
      </Head>
      <main>
        <Modal tittle="Atention" body={msgBody} />
        <CarrouselMovies
          tittle="Top rated movies"
          serviceTools={{ service: serviceGetTopRatedMovies }}
        />
        <CarrouselMovies
          tittle="Popular movies"
          serviceTools={{ service: serviceGetPopularMovies }}
        />
        <CarrouselMovies
          tittle="Upcoming movies"
          serviceTools={{ service: serviceGetUpcomingMovies }}
        />
      </main>
    </>
  );
}
